### ISSUE TITLE
How to add custom fields?

### ISSUE THREAD

**Issue by sbiefeni** [timekit-io/booking-js#93] opened 2016-04-07 23:08 UTC
I would like to add more custom fields to the booking form.. Is there any way to do this?

**Comment by laander** [comment] 2016-04-08 06:57
Hi @sbiefeni, currently we only support a fixed set of fields, see here: https://github.com/timekit-io/booking-js#--bookingfields 
Which would you like in addition to those?

**Comment by sbiefeni** [comment] 2016-04-08 17:18
Hi Lasse,

I am setting up a consultation booking page for a client, and your widget
is ideal, however my client really needs to be able to have a few custom
fields to get some preliminary information for the consultation.. I can see
that the use-case for this should be very common and necessary. I also
observed several forum requests asking for the same. I saw that some were
able to customize fields by editing the booking.js file.. however I haven't
figured out how they accomplished that yet.


*Stefano Biefeni*
Mobile: *778.384.8738* <778.384.8738>
Email: *stefano@abstractsoftware.ca* <stefano@abstractsoftware.ca>
Website: *www.abstractsoftware.ca* <http://www.abstractsoftware.ca>
[image: photo]
<http://ca.linkedin.com/in/stefanobiefeni>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=149775319615817>

**Comment by laander** [comment] 2016-04-13 14:25
@sbiefeni Could you list the fields (name and type) you'd like supported? It would allow us to focus in on the use-case and as a first step add more fields you can enable/disable (with true custom fields coming in the future)

**Comment by laander** [comment] 2016-04-13 14:26
Note: duplicate of #53

**Comment by sbiefeni** [comment] 2016-04-14 00:35
It doesn't make sense to have more pre-defined fields.. each use case will be different. In my last site, I needed to ask appointment specific questions - which Sutton Office are you Located In,  Are you interested in buying or selling, etc. As you see the only thing that makes sense is custom text fields, which all get added to the calendar "Description" field.

**Comment by zerosicks** [comment] 2016-06-24 23:44
+1

**Comment by laander** [comment] 2016-06-27 09:15
Closing this to keep discussion in #53

**Closed by laander** 2016-06-27 09:15 UTC
Labels: duplicate, feature request
