### ISSUE TITLE
Calendar initially displays available times during the following week even though the current week has available times

### ISSUE THREAD

**Issue by monfresh** [timekit-io/booking-js#51] opened 2015-12-09 04:59 UTC
The only setting that I could find that would affect this is `goToFirstEvent`, and whether I set it to `true` or `false`, the calendar always displays next week instead of this week. My filters are as follows:
```javascript
timekitFindTime: {
  future: '1 week',
  "filters": {
    "or": [
      { "specific_day_and_time": {"day": "Monday", "start": 20, "end": 22}},
      { "specific_day_and_time": {"day": "Tuesday", "start": 20, "end": 22}},
      { "specific_day_and_time": {"day": "Wednesday", "start": 20, "end": 22}},
      { "specific_day_and_time": {"day": "Thursday", "start": 20, "end": 22}},
      { "specific_day_and_time": {"day": "Friday", "start": 20, "end": 23}},
      { "specific_day_and_time": {"day": "Saturday", "start": 14, "end": 22}},
      { "specific_day_and_time": {"day": "Sunday", "start": 14, "end": 20}}
    ]
  }
}
```
Is there some other setting that could be used to define which week shows up by default?

**Comment by laander** [comment] 2015-12-09 13:57
Hi @monfresh 

This seems weird to me as `goToFirstEvent` will check the first event returned and navigate to that date (the week it resides in). There is a potential conflict when using the any of the following filters:
```
   "filters": {
       "after": [
           { "take_last": {"number": 4 } },
           { "take_random": {"number": 2 } }
       ]
   },
```
or the result sorting option: 
```
   "sort": "asc"
```
as all of these in some way changes the order of the results. I think there's something else going on. 

If you want, you can disable `goToFirstEvent` and pass in the following fullCalendar setting to set the initial date/week to display manually: http://fullcalendar.io/docs/current_date/defaultDate/
This can be done like so:
```
fullCalendar: {
  defaultDate: '2015-12-09T14:56:48+00:00'
}
```

**Comment by monfresh** [comment] 2015-12-12 04:15
I figured out the issue. I was wrong about setting `goToFirstEvent` to `false`. It's working as expected, which is that it defaults to today since that is what fullCalendar defaults to when `defaultDate` is not specified.

The issue when setting  `goToFirstEvent` to `true` is that it is basing its decision on the filters. As you can see in my original post, my filters started on Monday. Because of that, `goToFirstEvent` is looking for the first event that starts on Monday or later, even if there is an event on Saturday on an earlier date.

When I switched the order of my filters to put Saturday first, the calendar showed the event happening this week, as expected, but that solution will only last until Sunday :smile:

**Comment by laander** [comment] 2016-01-07 12:55
@monfresh Good catch! Actually, the intended result is achievable if you add the following setting 
```
timekitFindTime: {
  sort: "desc"
}
```
..as that will force the algorithm to do a sorting before returning the result. This *should* happen by default, but it doesn't right now, so we will be deploying a fix for this within today or tomorrow :+1: (in other words, just give us a day or two and everything should work as intended automatically)

**Comment by laander** [comment] 2016-01-12 15:26
@monfresh 
We've just updated the API so that `sort: "asc"` is the default behaviour when no sort key is provided. That should solve your problem - do let me know if that's not the case :+1:

**Closed by laander** 2016-01-12 15:26 UTC
Labels: bug, question

**Comment by monfresh** [comment] 2016-01-13 03:36
Thanks, it's working great now!
